export const pickUpLines = [
  "Are you a bible verse? Because I can't get you out of my head.",
  "Are you a church? Because you're a sanctuary.",
  "I was reading the book of Numbers the other day and I realized that I still dont have yours.",
  "I was going to read Proverbs 31, but then I realized that I can just study you.",
  "The Bible says “Give drink to those who are thirsty and feed the hungry.” So, how about dinner?",
  "Hey, let me check your tag…looks like I was right….Made in Heaven!",
  "Hi, I heard that God called you. Can I do the same?",
  "I believe one of my ribs belongs to you.",
  "Is your name Grace? Because you are amazing!",
  "Is your name Eve? Because you are the only woman in my world.",
  "When I count my blessings I make sure to count you twice.",
  "I would leave the 99 sheep to come find you…and then I would happily carry you home on my shoulders.",
  "Is it a sin that you stole my heart?",
  "You are just like a Bible verse because I cant stop memorizing you.",
  "You must be a fruit of the Spirit because you are so sweet.",
  "I might not be a prophet, but I can see a future with you.",
  "Sing hymns to our future children please",
  "The Bible says let our requests be made known unto God…well, I prayed and here you are.",
  "You can just call me Pharaoh. Cause Im never gonna give you up, never gonna let you go.",
  "Is the seat next to you saved? Because I am.",
  "What is your name and number so I can add you to my prayer list?",
  "The Bible talks about being led by the Spirit. I think the Spirit led me to you.",
  "I would say “God bless you”, but it looks like He already has.",
  "Ephesians 4: 29 says our words should lift others up and I am lifted up every time I hear your sweet voice!",
  "If we were there with Noah, you and me would be a pair.",
  "I know Moses parted the Red Sea, but nothing could part you and I.",
  "Is your name Adam? Because, to me, you are the only man in the world.",
  "You must be a fisher of men because you just caught me!",
  "I love how you look while reading the Bible, perhaps we can read together sometime.",
  "I pray every night for God to lead, guide, and direct me…and I think He is leading me straight to you.",
];
